---
kind: pipeline


steps:
- name: smoke test
  image: python:3.7
  commands:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run python3 -m pytest
  
- name: build release
  image: python:3.7
  commands:
    - python3 setup.py sdist bdist_wheel
  depends_on:
    - smoke test
